# Site settings
title: shakey
email: jcai@ganshane.com
description: > # this means to ignore newlines until "baseurl:"
  powered by you!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ganshane.github.io" # the base hostname & protocol for your site
twitter_username: freedom
github_username:  jcai

# Build settings
markdown: kramdown
